### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by AyzrixYTB** [HighLev-PM/SeedsPlus#1]
Add a cancelled in FactionClaim and in Protected Area with IProtector ^^

**Comment by Seyz123** [comment]
ptdr t ki

**Comment by Hirss** [comment]
genre ayzrix utilise mon plugin

**Comment by AyzrixYTB** [comment]
Nan j'utilise pas les plugins de gay. Mais j'aime aidé les gay comme toi Mev

**Comment by Hirss** [comment]
ya un bouton pour ban sur github ? lel

**Comment by AyzrixYTB** [comment]
😂 nan srx prend en considération ma suggestion

**Comment by Hirss** [comment]
ok chavez pas en vrai cimer bg

**Comment by YumikoMC** [comment]
Merci pour ta remarque constructive Ayrix
